[package]
name = "auth-service"
version = "0.1.0"
edition = "2024"
authors = ["M.MEZNI"]
description = "Bornemap"

[dependencies]
# Web framework
actix-web = "4.12.1"
actix-cors = "0.7.1"

# Async runtime
tokio = { version = "1.48.0", features = ["full"] }

# Database
sqlx = { version = "0.8.6", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"] }

# Serialization
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

# Error handling
anyhow = "1.0.100"
thiserror = "2.0.17"

# Logging
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "json"] }
tracing-actix-web = "0.7.20"

# Configuration
dotenvy = "0.15.7"

# OpenAPI/Swagger
utoipa = { version = "5.4.0", features = ["actix_extras", "chrono", "uuid"] }
utoipa-swagger-ui = { version = "9.0.2", features = ["actix-web"] }

# Utilities
chrono = { version = "0.4.42", features = ["serde"] }
uuid = { version = "1.19.0", features = ["v4", "serde"] }
nanoid = "0.4.0"
validator = { version = "0.20.0", features = ["derive"] }

# HTTP client for Keycloak
reqwest = { version = "0.12.25", features = ["json"] }

# Security
bcrypt = "0.17.1"
jsonwebtoken = { version = "10.2.0", features = ["rust_crypto"] }

# GeoIP
maxminddb = "0.27.0"
async-trait = "0.1.89"
futures = "0.3.31"
futures-util = "0.3.31"
