[server]
host = "127.0.0.1"
port = 3000

[database]
host = "localhost"
port = 5432
username = "postgres"
password = "password"
database_name = "auth_service_dev"

[keycloak]
server_url = "http://localhost:8080"

[logging]
level = "debug"
