services:
  postgres:
    image: postgres:18.1-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - 6500:5432
    volumes:
      - auth_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "postgres", "-U", "${AUTH_DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rust_app_no_api_network

volumes:
  auth_db_data:

networks:
  rust_app_no_api_network: